### ISSUE TITLE
Evaluate alternatives for oscillator

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/hardware-v2#1]
Can/should we use a different one than on the previous board?

**Comment by rnestler** [comment]
We should probably use the one recommended by the uC datasheet :wink:

**Comment by dbrgn** [comment]
I did some more research in how to pick an oscillator and how to choose the capacitance.

I found these two links:

- [ST AN2867](https://www.st.com/content/ccc/resource/technical/document/application_note/c6/eb/5e/11/e3/69/43/eb/CD00221665.pdf/files/CD00221665.pdf/jcr:content/translations/en.CD00221665.pdf)
- https://blog.adafruit.com/2012/01/24/choosing-the-right-crystal-and-caps-for-your-design/

The oscillator we picked ([NX3215SA-32.768KHZ-EXS00A-MU00525](https://www.digikey.com/products/en?keywords=644-1386-1-ND)) has a load capacitance of 6 pF. Using the formula `(C*C) / (C+C) + Cs = 6` and a `C` value of 4.3 pF (the value we picked in the schematics right now), we end up with a stray capacitance of 3.85 pF to reach the target `6 pF`. However, the [datasheet](https://github.com/gfroerli/hardware-v2/blob/master/datasheets/stm32l071xxx.pdf) says that `10 pF` can be used as a rough estimate of Cs:

![10pf_000](https://user-images.githubusercontent.com/105168/69874903-7be55480-12bc-11ea-8514-24541d79f6cb.png)

This text was about the HSE (high-speed) while the 32 kHz oscillator we use is a LSE. Does that guide still apply? Is this something we should test experimentally once we have a PCB?

**Comment by rnestler** [comment]
Well we used the same values as the nucleo board, so I think we are fine.

**Comment by dbrgn** [comment]
This can be closed, right?
