### ISSUE TITLE
Add solder bridges to disconnect parts of the circuit from power

### ISSUE THREAD

**Issue by rnestler** [gfroerli/hardware-v2#11]
This allows to measure power usage of components separately.

**Comment by dbrgn** [comment]
Since we don't have a solder bridge / 0 ohm resistor device yet, create it in the gfrörli library (and create a PR against the official library).

**Comment by dbrgn** [comment]
We can simply use a standard resistor with a value of 0 Ω.

**Comment by dbrgn** [comment]
Solder jumper sym/cmp added here: https://github.com/LibrePCB-Libraries/LibrePCB_Base.lplib/pull/52

But no packages yet. We could create a device that uses a chip resistor package in the meantime.

**Comment by rnestler** [comment]
For the solder bridges one would want something like ![](https://i.stack.imgur.com/iis71.jpg) for the footprint.

**Comment by rnestler** [comment]
We decided against doing this for everything, due to space constraints. So just for the SHTC3.
