### ISSUE TITLE
Allow disconnecting RN from rest of the board

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/hardware-v2#12]
This would allow flashing it without affecting the uC.

**Comment by rnestler** [comment]
So there are two issues right?:
 * Short circuits  / conflicts on the UART pins
 * The 9V on the NRST pin when using the ICP

**Comment by dbrgn** [comment]
> Short circuits / conflicts on the UART pins

Are there UART conflicts?

> The 9V on the NRST pin when using the ICP

Yep, that's the main issue.

**Comment by rnestler** [comment]
> Are there UART conflicts?

Well yes: The PC sends stuff to update the FW and the uC sends stuff to send measurements over LoRa.

**Comment by dbrgn** [comment]
Yeah, but during FW upgrade the uC should not be running at all, so that shouldn't be an issue.

**Comment by rnestler** [comment]
> Yeah, but during FW upgrade the uC should not be running at all, so that shouldn't be an issue.

But then we need to take care to not powering the uC through the UART pins, which could lead to strange effects.

**Comment by dbrgn** [comment]
Ok, good point. I wasn't aware that this could happen :)

**Comment by rnestler** [comment]
> > The 9V on the NRST pin when using the ICP
>
> Yep, that's the main issue.

After thinking about it, the 10k resistor already protects the 3.3V rails from the 9V, but PA4 of the micro controller is also connected to it. So we'd need to protect that pin.

**Comment by rnestler** [comment]
> Yeah, but during FW upgrade the uC should not be running at all, so that shouldn't be an issue.

We could pull the reset pin of the uC to low during FW upgrade of the RN module.

**Comment by dbrgn** [comment]
That could work. It's not currently accessible through a header though, right?

**Comment by dbrgn** [comment]
Power can be disconnected using the JP1 jumper.

If we need to reset the uC by pulling down STM_NRST, we can add a connection across C8.
