### ISSUE TITLE
Connector for Power

### ISSUE THREAD

**Issue by rnestler** [gfroerli/hardware-v2#15]
In a lab environment it's more practical to use a bench-top power supply than a battery.

**Comment by dbrgn** [comment]
We decided to go with a Micro-USB connector for now.

@rnestler do we need protection against having both the battery and USB connected, or do we assume everybody that connects power to the USB connector knows what they're doing?

Might battery power (3-4V) going *into* the USB connector damage the computer as well?

**Comment by rnestler** [comment]
> Might battery power (3-4V) going into the USB connector damage the computer as well?

We discussed this right? The conclusion was using the jumper as protection right?

**Comment by dbrgn** [comment]
Yep!
