### ISSUE TITLE
Think about DS18B20 pull up resistor value

### ISSUE THREAD

**Issue by rnestler** [gfroerli/hardware-v2#16]
![ds18b20](https://user-images.githubusercontent.com/1435346/32516672-6a047f38-c404-11e7-8245-9a3cba6dceec.png)
Do we need such a low resistance pull-up? (power consumtion...)

But this is a minor issue, since it doesn't influence the PCB. We can change it later.

**Comment by dbrgn** [comment]
https://www.maximintegrated.com/en/support/faqs/ds18b20-faq.html

>  Is the 4.7kΩ resistor needed for 5V and 3.3V operation?
> Yes, the 4.7kΩ pullup resistor is required for both 5V and 3.3V applications.
