### ISSUE TITLE
Connect RN2483 with antenna

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/hardware-v2#30]
I gave it a try.

[Specs used by Aisler](https://aisler.net/help/design-rules-and-specifications/specifications):

- [FR-4-86](https://aisler.net/help/design-rules-and-specifications/specifications/2_layer_datasheet.pdf)
  - Dielectric constant / permittivity @ 1 MHz: Max 5.4 Measured 4.7
  - Loss Tangent @ 1 MHz: Max 0.035 Measured 0.02
- Copper thickness: 35 µm

With 1.6mm board thickness and 0.3mm plane clearance:

![1](https://user-images.githubusercontent.com/105168/70182295-df6be980-16e3-11ea-8fdb-d6ca1f323062.png)

With 2mm board thickness:

![2](https://user-images.githubusercontent.com/105168/70182367-fd394e80-16e3-11ea-98c0-6aff2ae804cc.png)

I assumed 1.6mm thickness and made an attempt at drawing the trace:

![trace](https://user-images.githubusercontent.com/105168/70182425-1c37e080-16e4-11ea-811a-0b144e2ede28.png)

With the 1.415mm trace width we're at 50.0016 Ohms.

The length is roughly 17.44mm, this results in an angle(?) of 29.94°.

Does this look good? Are the input values correct? What does the angle mean?

**Comment by dbrgn** [comment]
Interestingly, the [RN2483 datasheet](http://ww1.microchip.com/downloads/en/DeviceDoc/50002346C.pdf) suggests a different design:

![routing](https://user-images.githubusercontent.com/105168/70182822-e515ff00-16e4-11ea-9ea7-dbed278e5d51.png)

**Comment by dbrgn** [comment]
Note: The edge mount SMA connector is made for a board thickness of 1.57mm (space is 1.73mm).

**Comment by rnestler** [comment]
> What does the angle mean?

Probably the resulting phase shift of the signal. Should increase proportional with the length of the trace.

**Comment by rnestler** [comment]
In the old board we made it like this;
![old-pcb_000](https://user-images.githubusercontent.com/1435346/70377226-28a18080-1912-11ea-80b6-70492ff0fc8f.png)
Since it worked quite well I guess we are fine as well.

Could you document all the decision making and sources for the PCB specs etc. in the `docs` folder?

**Comment by dbrgn** [comment]
> Since it worked quite well I guess we are fine as well.

Ok! I'll also add a few more vias around the trace.

> Could you document all the decision making and sources for the PCB specs etc. in the docs folder?

Yep, can do that!

**Comment by dbrgn** [comment]
> Probably the resulting phase shift of the signal. Should increase proportional with the length of the trace.

Yep, it does. Is it relevant for us?

**Comment by rnestler** [comment]
> Plane clearance: 0.3mm

On https://aisler.net/help/design-rules-and-specifications/2-and-4-layer-design-rules it says that the min. spacing trace / ground plane is 0.2mm

**Comment by dbrgn** [comment]
Ah, that part is not a spec by Aisler, it's the plane configuration we're using right now. I should have moved it to a different section, will fix.

**Comment by dbrgn** [comment]
Ok, stitching vias added. Should be OK now.

**Comment by dbrgn** [comment]
Note: Footprint replaced with [this one](https://www.digikey.ch/products/en?keywords=%20CON-SMA-EDGE-S) due to price (1.68 CHF instead of >10).

![conn](https://user-images.githubusercontent.com/105168/70758851-8d127480-1d44-11ea-8ba8-ce59b8ada105.png)

The connector seems to be basically the same as the [Samtec SMA-J-P-H-ST-EM1](https://www.digikey.com/product-detail/en/samtec-inc/SMA-J-P-H-ST-EM1/SAM8857-ND/2602450).
