### ISSUE TITLE
SMA connector fixes

### ISSUE THREAD

**Issue by dbrgn** [gfroerli/hardware-v2#31]
![image](https://user-images.githubusercontent.com/105168/70182914-14c50700-16e5-11ea-9b94-8e09e4297af9.png)

Either remove those vias, or connect them to the GND net.

**Comment by rnestler** [comment]
Is this really fixed? It still shows up as a DRC error for me :/

**Comment by dbrgn** [comment]
> Is this really fixed? It still shows up as a DRC error for me :/

Hm, you mean these errors?

![img](https://tmp.dbrgn.ch/screenshots/screenshot-20191210202706-kdwlh__9.png)

Strange, clearance between "GND" and ""... Looks like a bug to me.

The device looks like this:

![img](https://tmp.dbrgn.ch/screenshots/screenshot-20191210203053-66cw2wix.png)

So the two pads are connected to the same net as the GND legs.
