### ISSUE TITLE
Add button to WKUP1

### ISSUE THREAD

**Issue by rnestler** [gfroerli/hardware-v2#8]
It would be nice to wake up the device externally:
 * It enables us to trigger a measurement, which is nice for testing
 * If the device is in sleep sending commands / debugging via UART won't be possible.

**Comment by dbrgn** [comment]
> ### Standby mode with RTC
> 
> The device exits Standby mode in 60 μs when an external reset (NRST pin), an IWDG
> reset, a rising edge on one of the three WKUP pins, RTC alarm (Alarm A or Alarm B),
> RTC tamper event, RTC timestamp event or RTC Wakeup event occurs.
> 
> ### Standby mode without RTC
> 
> The device exits Standby mode in 60 μs when an external reset (NRST pin) or a rising
> edge on one of the three WKUP pin occurs.
